apiVersion: v1
kind: Service
metadata:
  name: my-kube-service
spec:
  type: NodePort
  selector:
    app: dmitriyf7498-kubesingleapp # ДОЛЖНО совпадать с labels в Deployment
  ports:
    - protocol: TCP
      port: 8092        # Порт самого сервиса внутри кластера
      targetPort: 8092   # Порт, который слушает приложение в контейнере
      nodePort: 30001  # Внешний порт (можно не указывать, K8s выберет сам)